package com.example.engine

import com.example.data.model.BiodataTemplate
import com.example.data.model.BiodataType

object TemplateRegistry {

    private val marriageTemplates: List<BiodataTemplate> = listOf(
        // 1 - 10: Royal & Luxury
        BiodataTemplate(
            id = "m_royal_gold_1",
            type = BiodataType.MARRIAGE,
            name = "Royal Gold Heritage",
            category = "Royal",
            isPaid = false,
            price = 0,
            layoutType = "ROYAL_BORDER",
            primaryColorHex = "#9A7B38",
            secondaryColorHex = "#F4EBD0",
            accentColorHex = "#C5A059",
            borderStyle = "DOUBLE_GOLD",
            headerStyle = "GANESHA",
            fontStyle = "SERIF",
            displayOrder = 1
        ),
        BiodataTemplate(
            id = "m_royal_maroon_2",
            type = BiodataType.MARRIAGE,
            name = "Imperial Maroon Palace",
            category = "Royal",
            isPaid = true,
            price = 49,
            layoutType = "ROYAL_BORDER",
            primaryColorHex = "#7B1113",
            secondaryColorHex = "#F9F1F0",
            accentColorHex = "#D4AF37",
            borderStyle = "ORNATE",
            headerStyle = "CREST",
            fontStyle = "SERIF",
            displayOrder = 2
        ),
        BiodataTemplate(
            id = "m_royal_navy_3",
            type = BiodataType.MARRIAGE,
            name = "Crown Sapphire Crest",
            category = "Royal",
            isPaid = true,
            price = 49,
            layoutType = "SIDEBAR_LEFT",
            primaryColorHex = "#0F2042",
            secondaryColorHex = "#EEF2F6",
            accentColorHex = "#C6A052",
            borderStyle = "MODERN_BAR",
            headerStyle = "CREST",
            fontStyle = "SERIF",
            displayOrder = 3
        ),
        BiodataTemplate(
            id = "m_royal_emerald_4",
            type = BiodataType.MARRIAGE,
            name = "Emerald Dynasty",
            category = "Royal",
            isPaid = false,
            price = 0,
            layoutType = "CLASSIC_HEADER",
            primaryColorHex = "#0C3823",
            secondaryColorHex = "#EBF4EF",
            accentColorHex = "#A88434",
            borderStyle = "DOUBLE_GOLD",
            headerStyle = "GANESHA",
            fontStyle = "SERIF",
            displayOrder = 4
        ),
        BiodataTemplate(
            id = "m_royal_purple_5",
            type = BiodataType.MARRIAGE,
            name = "Regal Amethyst Arch",
            category = "Royal",
            isPaid = true,
            price = 39,
            layoutType = "ROYAL_BORDER",
            primaryColorHex = "#4A154B",
            secondaryColorHex = "#F6EEF7",
            accentColorHex = "#E2B857",
            borderStyle = "ORNATE",
            headerStyle = "CREST",
            fontStyle = "SERIF",
            displayOrder = 5
        ),
        BiodataTemplate(
            id = "m_royal_ruby_6",
            type = BiodataType.MARRIAGE,
            name = "Velvet Ruby Scroll",
            category = "Royal",
            isPaid = false,
            price = 0,
            layoutType = "TWO_COLUMN",
            primaryColorHex = "#800020",
            secondaryColorHex = "#FAF0F2",
            accentColorHex = "#D4AF37",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SERIF",
            displayOrder = 6
        ),
        BiodataTemplate(
            id = "m_royal_pearl_7",
            type = BiodataType.MARRIAGE,
            name = "Pearl & Filigree",
            category = "Royal",
            isPaid = true,
            price = 29,
            layoutType = "CLASSIC_HEADER",
            primaryColorHex = "#665C54",
            secondaryColorHex = "#FDFBF7",
            accentColorHex = "#D4AF37",
            borderStyle = "ORNATE",
            headerStyle = "GANESHA",
            fontStyle = "SERIF",
            displayOrder = 7
        ),
        BiodataTemplate(
            id = "m_royal_bronze_8",
            type = BiodataType.MARRIAGE,
            name = "Antique Bronze Court",
            category = "Royal",
            isPaid = false,
            price = 0,
            layoutType = "SIDEBAR_RIGHT",
            primaryColorHex = "#5E4833",
            secondaryColorHex = "#F8F5F1",
            accentColorHex = "#B8977E",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SERIF",
            displayOrder = 8
        ),
        BiodataTemplate(
            id = "m_royal_damask_9",
            type = BiodataType.MARRIAGE,
            name = "Royal Damask Motif",
            category = "Royal",
            isPaid = true,
            price = 49,
            layoutType = "ROYAL_BORDER",
            primaryColorHex = "#8B1E3F",
            secondaryColorHex = "#FBF4F6",
            accentColorHex = "#CBB26B",
            borderStyle = "DOUBLE_GOLD",
            headerStyle = "CREST",
            fontStyle = "SERIF",
            displayOrder = 9
        ),
        BiodataTemplate(
            id = "m_royal_monarch_10",
            type = BiodataType.MARRIAGE,
            name = "Monarch Gold Foil",
            category = "Royal",
            isPaid = true,
            price = 79,
            layoutType = "DARK_LUXURY",
            primaryColorHex = "#1C1C1E",
            secondaryColorHex = "#2C2C2E",
            accentColorHex = "#ECC870",
            backgroundColorHex = "#18181A",
            borderStyle = "DOUBLE_GOLD",
            headerStyle = "CREST",
            fontStyle = "SERIF",
            displayOrder = 10
        ),

        // 11 - 20: Traditional & Indian Heritage
        BiodataTemplate(
            id = "m_trad_shree_11",
            type = BiodataType.MARRIAGE,
            name = "Shree Ganesha Vedic",
            category = "Traditional",
            isPaid = false,
            price = 0,
            layoutType = "TRADITIONAL_HERITAGE",
            primaryColorHex = "#B33924",
            secondaryColorHex = "#FFF6F4",
            accentColorHex = "#E08E45",
            borderStyle = "ORNATE",
            headerStyle = "GANESHA",
            fontStyle = "SERIF",
            displayOrder = 11
        ),
        BiodataTemplate(
            id = "m_trad_mandala_12",
            type = BiodataType.MARRIAGE,
            name = "Sacred Mandala Aura",
            category = "Traditional",
            isPaid = true,
            price = 29,
            layoutType = "TRADITIONAL_HERITAGE",
            primaryColorHex = "#A24857",
            secondaryColorHex = "#FFF5F7",
            accentColorHex = "#C99A45",
            borderStyle = "ORNATE",
            headerStyle = "GANESHA",
            fontStyle = "SERIF",
            displayOrder = 12
        ),
        BiodataTemplate(
            id = "m_trad_temple_13",
            type = BiodataType.MARRIAGE,
            name = "Temple Pillar Classic",
            category = "Traditional",
            isPaid = false,
            price = 0,
            layoutType = "CLASSIC_HEADER",
            primaryColorHex = "#8C4A26",
            secondaryColorHex = "#FBF6F0",
            accentColorHex = "#C8864E",
            borderStyle = "DOUBLE_GOLD",
            headerStyle = "GANESHA",
            fontStyle = "SERIF",
            displayOrder = 13
        ),
        BiodataTemplate(
            id = "m_trad_sindoor_14",
            type = BiodataType.MARRIAGE,
            name = "Sindoor & Haldi Grace",
            category = "Traditional",
            isPaid = true,
            price = 39,
            layoutType = "TWO_COLUMN",
            primaryColorHex = "#C0392B",
            secondaryColorHex = "#FEF9E7",
            accentColorHex = "#F39C12",
            borderStyle = "ORNATE",
            headerStyle = "GANESHA",
            fontStyle = "SERIF",
            displayOrder = 14
        ),
        BiodataTemplate(
            id = "m_trad_banarasi_15",
            type = BiodataType.MARRIAGE,
            name = "Banarasi Zari Weave",
            category = "Traditional",
            isPaid = true,
            price = 49,
            layoutType = "ROYAL_BORDER",
            primaryColorHex = "#900C3F",
            secondaryColorHex = "#FDF2F4",
            accentColorHex = "#DFAC42",
            borderStyle = "ORNATE",
            headerStyle = "CREST",
            fontStyle = "SERIF",
            displayOrder = 15
        ),
        BiodataTemplate(
            id = "m_trad_shubh_16",
            type = BiodataType.MARRIAGE,
            name = "Shubh Vivah Lagan",
            category = "Traditional",
            isPaid = false,
            price = 0,
            layoutType = "TRADITIONAL_HERITAGE",
            primaryColorHex = "#A93226",
            secondaryColorHex = "#FDF2E9",
            accentColorHex = "#D4AC0D",
            borderStyle = "ORNATE",
            headerStyle = "GANESHA",
            fontStyle = "SERIF",
            displayOrder = 16
        ),
        BiodataTemplate(
            id = "m_trad_haveli_17",
            type = BiodataType.MARRIAGE,
            name = "Rajasthan Haveli Jharokha",
            category = "Traditional",
            isPaid = true,
            price = 39,
            layoutType = "ROYAL_BORDER",
            primaryColorHex = "#7D3C98",
            secondaryColorHex = "#F5EEF8",
            accentColorHex = "#F1C40F",
            borderStyle = "DOUBLE_GOLD",
            headerStyle = "CREST",
            fontStyle = "SERIF",
            displayOrder = 17
        ),
        BiodataTemplate(
            id = "m_trad_peacock_18",
            type = BiodataType.MARRIAGE,
            name = "Mayur Peacock Plume",
            category = "Traditional",
            isPaid = false,
            price = 0,
            layoutType = "SIDEBAR_LEFT",
            primaryColorHex = "#0B5345",
            secondaryColorHex = "#E8F8F5",
            accentColorHex = "#117864",
            borderStyle = "MODERN_BAR",
            headerStyle = "SIMPLE",
            fontStyle = "SERIF",
            displayOrder = 18
        ),
        BiodataTemplate(
            id = "m_trad_diya_19",
            type = BiodataType.MARRIAGE,
            name = "Mangal Kalash Diya",
            category = "Traditional",
            isPaid = true,
            price = 29,
            layoutType = "CLASSIC_HEADER",
            primaryColorHex = "#922B21",
            secondaryColorHex = "#FDEDEC",
            accentColorHex = "#B7950B",
            borderStyle = "ORNATE",
            headerStyle = "GANESHA",
            fontStyle = "SERIF",
            displayOrder = 19
        ),
        BiodataTemplate(
            id = "m_trad_paithani_20",
            type = BiodataType.MARRIAGE,
            name = "Maharashtrian Paithani Border",
            category = "Traditional",
            isPaid = true,
            price = 49,
            layoutType = "ROYAL_BORDER",
            primaryColorHex = "#6C3483",
            secondaryColorHex = "#F4ECF7",
            accentColorHex = "#F4D03F",
            borderStyle = "ORNATE",
            headerStyle = "GANESHA",
            fontStyle = "SERIF",
            displayOrder = 20
        ),

        // 21 - 30: Floral & Wedding Card Elegance
        BiodataTemplate(
            id = "m_floral_rose_21",
            type = BiodataType.MARRIAGE,
            name = "English Rose Garden",
            category = "Floral",
            isPaid = false,
            price = 0,
            layoutType = "WEDDING_FLORAL",
            primaryColorHex = "#A35D6A",
            secondaryColorHex = "#FFF5F6",
            accentColorHex = "#8B9A46",
            borderStyle = "ORNATE",
            headerStyle = "SIMPLE",
            fontStyle = "SERIF",
            displayOrder = 21
        ),
        BiodataTemplate(
            id = "m_floral_jasmine_22",
            type = BiodataType.MARRIAGE,
            name = "White Mogra Garland",
            category = "Floral",
            isPaid = true,
            price = 29,
            layoutType = "WEDDING_FLORAL",
            primaryColorHex = "#4A5859",
            secondaryColorHex = "#F8FAF8",
            accentColorHex = "#D6B85A",
            borderStyle = "HAIRLINE",
            headerStyle = "CREST",
            fontStyle = "SERIF",
            displayOrder = 22
        ),
        BiodataTemplate(
            id = "m_floral_lotus_23",
            type = BiodataType.MARRIAGE,
            name = "Sacred Pink Lotus",
            category = "Floral",
            isPaid = false,
            price = 0,
            layoutType = "CLASSIC_HEADER",
            primaryColorHex = "#B85D77",
            secondaryColorHex = "#FDF7F8",
            accentColorHex = "#748057",
            borderStyle = "DOUBLE_GOLD",
            headerStyle = "GANESHA",
            fontStyle = "SERIF",
            displayOrder = 23
        ),
        BiodataTemplate(
            id = "m_floral_marigold_24",
            type = BiodataType.MARRIAGE,
            name = "Genda Phool Festive",
            category = "Floral",
            isPaid = true,
            price = 39,
            layoutType = "ROYAL_BORDER",
            primaryColorHex = "#C06014",
            secondaryColorHex = "#FFFDF9",
            accentColorHex = "#F39C12",
            borderStyle = "ORNATE",
            headerStyle = "GANESHA",
            fontStyle = "SERIF",
            displayOrder = 24
        ),
        BiodataTemplate(
            id = "m_floral_botanical_25",
            type = BiodataType.MARRIAGE,
            name = "Sage Botanical Foliage",
            category = "Floral",
            isPaid = false,
            price = 0,
            layoutType = "TWO_COLUMN",
            primaryColorHex = "#4B6043",
            secondaryColorHex = "#F6F9F5",
            accentColorHex = "#8F9779",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 25
        ),
        BiodataTemplate(
            id = "m_floral_lavender_26",
            type = BiodataType.MARRIAGE,
            name = "French Lavender Mist",
            category = "Floral",
            isPaid = true,
            price = 29,
            layoutType = "WEDDING_FLORAL",
            primaryColorHex = "#6B5B95",
            secondaryColorHex = "#F7F5FA",
            accentColorHex = "#B5A7D6",
            borderStyle = "HAIRLINE",
            headerStyle = "CREST",
            fontStyle = "SERIF",
            displayOrder = 26
        ),
        BiodataTemplate(
            id = "m_floral_hibiscus_27",
            type = BiodataType.MARRIAGE,
            name = "Crimson Hibiscus Ribbon",
            category = "Floral",
            isPaid = true,
            price = 49,
            layoutType = "ROYAL_BORDER",
            primaryColorHex = "#9E2A2B",
            secondaryColorHex = "#FFF9F9",
            accentColorHex = "#DDA15E",
            borderStyle = "ORNATE",
            headerStyle = "GANESHA",
            fontStyle = "SERIF",
            displayOrder = 27
        ),
        BiodataTemplate(
            id = "m_floral_orchids_28",
            type = BiodataType.MARRIAGE,
            name = "Wild Orchid Bloom",
            category = "Floral",
            isPaid = false,
            price = 0,
            layoutType = "SIDEBAR_RIGHT",
            primaryColorHex = "#8338EC",
            secondaryColorHex = "#FAF7FD",
            accentColorHex = "#FFBE0B",
            borderStyle = "MODERN_BAR",
            headerStyle = "SIMPLE",
            fontStyle = "SERIF",
            displayOrder = 28
        ),
        BiodataTemplate(
            id = "m_floral_chrysanthemum_29",
            type = BiodataType.MARRIAGE,
            name = "Golden Chrysanthemum",
            category = "Floral",
            isPaid = true,
            price = 39,
            layoutType = "CLASSIC_HEADER",
            primaryColorHex = "#B08968",
            secondaryColorHex = "#FAF7F2",
            accentColorHex = "#7F5539",
            borderStyle = "DOUBLE_GOLD",
            headerStyle = "CREST",
            fontStyle = "SERIF",
            displayOrder = 29
        ),
        BiodataTemplate(
            id = "m_floral_boho_30",
            type = BiodataType.MARRIAGE,
            name = "Boho Pampas Meadow",
            category = "Floral",
            isPaid = false,
            price = 0,
            layoutType = "WEDDING_FLORAL",
            primaryColorHex = "#8D7B68",
            secondaryColorHex = "#F9F7F5",
            accentColorHex = "#C8B6A6",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SERIF",
            displayOrder = 30
        ),

        // 31 - 40: Modern, Minimal & Magazine
        BiodataTemplate(
            id = "m_mod_minimal_31",
            type = BiodataType.MARRIAGE,
            name = "Minimalist Vogue White",
            category = "Modern",
            isPaid = false,
            price = 0,
            layoutType = "MINIMAL_PORTRAIT",
            primaryColorHex = "#1F2937",
            secondaryColorHex = "#F9FAFB",
            accentColorHex = "#6B7280",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 31
        ),
        BiodataTemplate(
            id = "m_mod_magazine_32",
            type = BiodataType.MARRIAGE,
            name = "Editorial Profile Luxe",
            category = "Modern",
            isPaid = true,
            price = 49,
            layoutType = "MAGAZINE",
            primaryColorHex = "#111827",
            secondaryColorHex = "#F3F4F6",
            accentColorHex = "#D97706",
            borderStyle = "NONE",
            headerStyle = "SIMPLE",
            fontStyle = "SERIF",
            displayOrder = 32
        ),
        BiodataTemplate(
            id = "m_mod_sidebar_33",
            type = BiodataType.MARRIAGE,
            name = "Nordic Slate Column",
            category = "Modern",
            isPaid = false,
            price = 0,
            layoutType = "SIDEBAR_LEFT",
            primaryColorHex = "#334155",
            secondaryColorHex = "#F1F5F9",
            accentColorHex = "#0EA5E9",
            borderStyle = "MODERN_BAR",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 33
        ),
        BiodataTemplate(
            id = "m_mod_twocol_34",
            type = BiodataType.MARRIAGE,
            name = "Contemporary Grid Duo",
            category = "Modern",
            isPaid = true,
            price = 29,
            layoutType = "TWO_COLUMN",
            primaryColorHex = "#1E293B",
            secondaryColorHex = "#F8FAFC",
            accentColorHex = "#3B82F6",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 34
        ),
        BiodataTemplate(
            id = "m_mod_blush_35",
            type = BiodataType.MARRIAGE,
            name = "Blush Contemporary Chic",
            category = "Modern",
            isPaid = false,
            price = 0,
            layoutType = "MINIMAL_PORTRAIT",
            primaryColorHex = "#6D4C41",
            secondaryColorHex = "#FBE9E7",
            accentColorHex = "#D7CCC8",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SERIF",
            displayOrder = 35
        ),
        BiodataTemplate(
            id = "m_mod_indigo_36",
            type = BiodataType.MARRIAGE,
            name = "Midnight Indigo Studio",
            category = "Modern",
            isPaid = true,
            price = 49,
            layoutType = "SIDEBAR_RIGHT",
            primaryColorHex = "#1E1B4B",
            secondaryColorHex = "#EEF2FF",
            accentColorHex = "#6366F1",
            borderStyle = "MODERN_BAR",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 36
        ),
        BiodataTemplate(
            id = "m_mod_copper_37",
            type = BiodataType.MARRIAGE,
            name = "Brushed Copper Modern",
            category = "Modern",
            isPaid = true,
            price = 39,
            layoutType = "CLASSIC_HEADER",
            primaryColorHex = "#9C5238",
            secondaryColorHex = "#FDF7F5",
            accentColorHex = "#C67D5A",
            borderStyle = "HAIRLINE",
            headerStyle = "CREST",
            fontStyle = "SERIF",
            displayOrder = 37
        ),
        BiodataTemplate(
            id = "m_mod_compact_38",
            type = BiodataType.MARRIAGE,
            name = "Compact One-Pager Neat",
            category = "Modern",
            isPaid = false,
            price = 0,
            layoutType = "COMPACT_GRID",
            primaryColorHex = "#27272A",
            secondaryColorHex = "#FAFAFA",
            accentColorHex = "#10B981",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 38
        ),
        BiodataTemplate(
            id = "m_mod_taupe_39",
            type = BiodataType.MARRIAGE,
            name = "Warm Taupe Harmony",
            category = "Modern",
            isPaid = false,
            price = 0,
            layoutType = "MINIMAL_PORTRAIT",
            primaryColorHex = "#5C5248",
            secondaryColorHex = "#F5F2EF",
            accentColorHex = "#A3978B",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SERIF",
            displayOrder = 39
        ),
        BiodataTemplate(
            id = "m_mod_creme_40",
            type = BiodataType.MARRIAGE,
            name = "Crème Silhouette Clean",
            category = "Modern",
            isPaid = true,
            price = 29,
            layoutType = "TWO_COLUMN",
            primaryColorHex = "#3D3A36",
            secondaryColorHex = "#FAF8F5",
            accentColorHex = "#B39D82",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 40
        ),

        // 41 - 55: Distinctive Categories (Photo Focus, Family Focus, Dark Luxe, Regional)
        BiodataTemplate(
            id = "m_photo_spotlight_41",
            type = BiodataType.MARRIAGE,
            name = "Portrait Spotlight Hero",
            category = "Photo Focus",
            isPaid = false,
            price = 0,
            layoutType = "MAGAZINE",
            primaryColorHex = "#2B2D42",
            secondaryColorHex = "#EDF2F4",
            accentColorHex = "#D90429",
            borderStyle = "NONE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 41
        ),
        BiodataTemplate(
            id = "m_photo_circle_42",
            type = BiodataType.MARRIAGE,
            name = "Golden Medallion Portrait",
            category = "Photo Focus",
            isPaid = true,
            price = 39,
            layoutType = "CLASSIC_HEADER",
            primaryColorHex = "#43281C",
            secondaryColorHex = "#FDFBF7",
            accentColorHex = "#BB9457",
            borderStyle = "DOUBLE_GOLD",
            headerStyle = "CREST",
            fontStyle = "SERIF",
            displayOrder = 42
        ),
        BiodataTemplate(
            id = "m_fam_extended_43",
            type = BiodataType.MARRIAGE,
            name = "Family Heritage Focus",
            category = "Family Focus",
            isPaid = false,
            price = 0,
            layoutType = "TWO_COLUMN",
            primaryColorHex = "#540B0E",
            secondaryColorHex = "#FFF9F9",
            accentColorHex = "#9E2A2B",
            borderStyle = "HAIRLINE",
            headerStyle = "GANESHA",
            fontStyle = "SERIF",
            displayOrder = 43
        ),
        BiodataTemplate(
            id = "m_fam_lineage_44",
            type = BiodataType.MARRIAGE,
            name = "Khandan Parivar Pride",
            category = "Family Focus",
            isPaid = true,
            price = 49,
            layoutType = "ROYAL_BORDER",
            primaryColorHex = "#603813",
            secondaryColorHex = "#FDFCF7",
            accentColorHex = "#B2975B",
            borderStyle = "ORNATE",
            headerStyle = "GANESHA",
            fontStyle = "SERIF",
            displayOrder = 44
        ),
        BiodataTemplate(
            id = "m_dark_onyx_45",
            type = BiodataType.MARRIAGE,
            name = "Midnight Onyx & Gold",
            category = "Dark Luxury",
            isPaid = true,
            price = 99,
            layoutType = "DARK_LUXURY",
            primaryColorHex = "#121212",
            secondaryColorHex = "#1E1E1E",
            accentColorHex = "#F5C518",
            backgroundColorHex = "#151515",
            borderStyle = "DOUBLE_GOLD",
            headerStyle = "CREST",
            fontStyle = "SERIF",
            displayOrder = 45
        ),
        BiodataTemplate(
            id = "m_dark_sapphire_46",
            type = BiodataType.MARRIAGE,
            name = "Deep Navy Starline",
            category = "Dark Luxury",
            isPaid = true,
            price = 89,
            layoutType = "DARK_LUXURY",
            primaryColorHex = "#0A192F",
            secondaryColorHex = "#172A45",
            accentColorHex = "#64FFDA",
            backgroundColorHex = "#0C1B33",
            borderStyle = "HAIRLINE",
            headerStyle = "CREST",
            fontStyle = "SANS",
            displayOrder = 46
        ),
        BiodataTemplate(
            id = "m_dark_emerald_47",
            type = BiodataType.MARRIAGE,
            name = "Malachite Gold Prestige",
            category = "Dark Luxury",
            isPaid = true,
            price = 79,
            layoutType = "DARK_LUXURY",
            primaryColorHex = "#05201A",
            secondaryColorHex = "#0D332B",
            accentColorHex = "#E5B94E",
            backgroundColorHex = "#08241D",
            borderStyle = "DOUBLE_GOLD",
            headerStyle = "CREST",
            fontStyle = "SERIF",
            displayOrder = 47
        ),
        BiodataTemplate(
            id = "m_reg_punjabi_48",
            type = BiodataType.MARRIAGE,
            name = "Anand Karaj Heritage",
            category = "Traditional",
            isPaid = false,
            price = 0,
            layoutType = "TRADITIONAL_HERITAGE",
            primaryColorHex = "#B33771",
            secondaryColorHex = "#FDF7FA",
            accentColorHex = "#FD7272",
            borderStyle = "ORNATE",
            headerStyle = "CREST",
            fontStyle = "SERIF",
            displayOrder = 48
        ),
        BiodataTemplate(
            id = "m_reg_gujarati_49",
            type = BiodataType.MARRIAGE,
            name = "Bandhani Vivah Patrika",
            category = "Traditional",
            isPaid = true,
            price = 39,
            layoutType = "ROYAL_BORDER",
            primaryColorHex = "#D35400",
            secondaryColorHex = "#FEF5E7",
            accentColorHex = "#F39C12",
            borderStyle = "ORNATE",
            headerStyle = "GANESHA",
            fontStyle = "SERIF",
            displayOrder = 49
        ),
        BiodataTemplate(
            id = "m_reg_bengali_50",
            type = BiodataType.MARRIAGE,
            name = "Shubho Bibaha Alpana",
            category = "Traditional",
            isPaid = false,
            price = 0,
            layoutType = "CLASSIC_HEADER",
            primaryColorHex = "#A93226",
            secondaryColorHex = "#FDEDEC",
            accentColorHex = "#F1C40F",
            borderStyle = "ORNATE",
            headerStyle = "GANESHA",
            fontStyle = "SERIF",
            displayOrder = 50
        ),
        BiodataTemplate(
            id = "m_reg_south_51",
            type = BiodataType.MARRIAGE,
            name = "Kanjeevaram Temple Zari",
            category = "Traditional",
            isPaid = true,
            price = 49,
            layoutType = "ROYAL_BORDER",
            primaryColorHex = "#78281F",
            secondaryColorHex = "#FDF4F3",
            accentColorHex = "#B7950B",
            borderStyle = "DOUBLE_GOLD",
            headerStyle = "GANESHA",
            fontStyle = "SERIF",
            displayOrder = 51
        ),
        BiodataTemplate(
            id = "m_photo_banner_52",
            type = BiodataType.MARRIAGE,
            name = "Wide Landscape Banner",
            category = "Photo Focus",
            isPaid = false,
            price = 0,
            layoutType = "SIDEBAR_LEFT",
            primaryColorHex = "#264653",
            secondaryColorHex = "#EBF2F1",
            accentColorHex = "#2A9D8F",
            borderStyle = "MODERN_BAR",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 52
        ),
        BiodataTemplate(
            id = "m_classic_ivory_53",
            type = BiodataType.MARRIAGE,
            name = "Timeless Ivory Archival",
            category = "Classic",
            isPaid = false,
            price = 0,
            layoutType = "CLASSIC_HEADER",
            primaryColorHex = "#4A4036",
            secondaryColorHex = "#FBF9F5",
            accentColorHex = "#8C7B6B",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SERIF",
            displayOrder = 53
        ),
        BiodataTemplate(
            id = "m_royal_silver_54",
            type = BiodataType.MARRIAGE,
            name = "Sterling Silver Empress",
            category = "Royal",
            isPaid = true,
            price = 39,
            layoutType = "ROYAL_BORDER",
            primaryColorHex = "#4A5568",
            secondaryColorHex = "#EDF2F7",
            accentColorHex = "#CBD5E0",
            borderStyle = "DOUBLE_GOLD",
            headerStyle = "CREST",
            fontStyle = "SERIF",
            displayOrder = 54
        ),
        BiodataTemplate(
            id = "m_mod_champagne_55",
            type = BiodataType.MARRIAGE,
            name = "Champagne Luxe Signature",
            category = "Royal",
            isPaid = true,
            price = 69,
            layoutType = "ROYAL_BORDER",
            primaryColorHex = "#8C7355",
            secondaryColorHex = "#FDFBF7",
            accentColorHex = "#E5D4B8",
            borderStyle = "DOUBLE_GOLD",
            headerStyle = "CREST",
            fontStyle = "SERIF",
            displayOrder = 55
        )
    )

    private val jobTemplates: List<BiodataTemplate> = listOf(
        // 1 - 10: Executive & Corporate
        BiodataTemplate(
            id = "j_executive_blue_1",
            type = BiodataType.JOB,
            name = "Executive Corporate Navy",
            category = "Executive",
            isPaid = false,
            price = 0,
            layoutType = "EXECUTIVE_CORPORATE",
            primaryColorHex = "#1E3A8A",
            secondaryColorHex = "#EFF6FF",
            accentColorHex = "#3B82F6",
            borderStyle = "MODERN_BAR",
            headerStyle = "CORPORATE",
            fontStyle = "SANS",
            displayOrder = 1
        ),
        BiodataTemplate(
            id = "j_executive_slate_2",
            type = BiodataType.JOB,
            name = "Fortune C-Suite Leader",
            category = "Executive",
            isPaid = true,
            price = 49,
            layoutType = "EXECUTIVE_CORPORATE",
            primaryColorHex = "#0F172A",
            secondaryColorHex = "#F8FAFC",
            accentColorHex = "#0EA5E9",
            borderStyle = "MODERN_BAR",
            headerStyle = "CORPORATE",
            fontStyle = "SANS",
            displayOrder = 2
        ),
        BiodataTemplate(
            id = "j_executive_teal_3",
            type = BiodataType.JOB,
            name = "Strategy Director Teal",
            category = "Executive",
            isPaid = false,
            price = 0,
            layoutType = "SIDEBAR_LEFT",
            primaryColorHex = "#115E59",
            secondaryColorHex = "#F0FDFA",
            accentColorHex = "#14B8A6",
            borderStyle = "MODERN_BAR",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 3
        ),
        BiodataTemplate(
            id = "j_executive_oxford_4",
            type = BiodataType.JOB,
            name = "Oxford Academic Fellow",
            category = "Executive",
            isPaid = true,
            price = 39,
            layoutType = "CLASSIC_HEADER",
            primaryColorHex = "#1E293B",
            secondaryColorHex = "#F8FAFC",
            accentColorHex = "#64748B",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SERIF",
            displayOrder = 4
        ),
        BiodataTemplate(
            id = "j_executive_burgundy_5",
            type = BiodataType.JOB,
            name = "Managing Partner Burgundy",
            category = "Executive",
            isPaid = true,
            price = 49,
            layoutType = "SIDEBAR_LEFT",
            primaryColorHex = "#881337",
            secondaryColorHex = "#FFF1F2",
            accentColorHex = "#E11D48",
            borderStyle = "MODERN_BAR",
            headerStyle = "SIMPLE",
            fontStyle = "SERIF",
            displayOrder = 5
        ),
        BiodataTemplate(
            id = "j_executive_steel_6",
            type = BiodataType.JOB,
            name = "Steel Grey Enterprise",
            category = "Executive",
            isPaid = false,
            price = 0,
            layoutType = "TWO_COLUMN",
            primaryColorHex = "#374151",
            secondaryColorHex = "#F3F4F6",
            accentColorHex = "#4B5563",
            borderStyle = "HAIRLINE",
            headerStyle = "CORPORATE",
            fontStyle = "SANS",
            displayOrder = 6
        ),
        BiodataTemplate(
            id = "j_executive_gold_7",
            type = BiodataType.JOB,
            name = "Prime Advisory Gold",
            category = "Executive",
            isPaid = true,
            price = 69,
            layoutType = "EXECUTIVE_CORPORATE",
            primaryColorHex = "#18181B",
            secondaryColorHex = "#FAFAFA",
            accentColorHex = "#D97706",
            borderStyle = "DOUBLE_GOLD",
            headerStyle = "CORPORATE",
            fontStyle = "SERIF",
            displayOrder = 7
        ),
        BiodataTemplate(
            id = "j_executive_royal_8",
            type = BiodataType.JOB,
            name = "Global Banking Cobalt",
            category = "Executive",
            isPaid = false,
            price = 0,
            layoutType = "SIDEBAR_LEFT",
            primaryColorHex = "#1D4ED8",
            secondaryColorHex = "#EFF6FF",
            accentColorHex = "#60A5FA",
            borderStyle = "MODERN_BAR",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 8
        ),
        BiodataTemplate(
            id = "j_executive_charcoal_9",
            type = BiodataType.JOB,
            name = "Charcoal Consulting",
            category = "Executive",
            isPaid = true,
            price = 29,
            layoutType = "CLASSIC_HEADER",
            primaryColorHex = "#1F2937",
            secondaryColorHex = "#F9FAFB",
            accentColorHex = "#4B5563",
            borderStyle = "HAIRLINE",
            headerStyle = "CORPORATE",
            fontStyle = "SANS",
            displayOrder = 9
        ),
        BiodataTemplate(
            id = "j_executive_emerald_10",
            type = BiodataType.JOB,
            name = "Venture Partner Pine",
            category = "Executive",
            isPaid = true,
            price = 49,
            layoutType = "TWO_COLUMN",
            primaryColorHex = "#064E3B",
            secondaryColorHex = "#ECFDF5",
            accentColorHex = "#059669",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 10
        ),

        // 11 - 20: Modern & Creative
        BiodataTemplate(
            id = "j_mod_accent_11",
            type = BiodataType.JOB,
            name = "Silicon Valley Creative Accent",
            category = "Creative",
            isPaid = false,
            price = 0,
            layoutType = "CREATIVE_ACCENT",
            primaryColorHex = "#4F46E5",
            secondaryColorHex = "#EEF2FF",
            accentColorHex = "#818CF8",
            borderStyle = "NONE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 11
        ),
        BiodataTemplate(
            id = "j_mod_sunset_12",
            type = BiodataType.JOB,
            name = "Sunset Coral Designer",
            category = "Creative",
            isPaid = true,
            price = 39,
            layoutType = "CREATIVE_ACCENT",
            primaryColorHex = "#BE185D",
            secondaryColorHex = "#FDF2F8",
            accentColorHex = "#FB7185",
            borderStyle = "NONE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 12
        ),
        BiodataTemplate(
            id = "j_mod_mint_13",
            type = BiodataType.JOB,
            name = "Fresh Mint Developer",
            category = "Modern",
            isPaid = false,
            price = 0,
            layoutType = "SIDEBAR_LEFT",
            primaryColorHex = "#0D9488",
            secondaryColorHex = "#F0FDFA",
            accentColorHex = "#2DD4BF",
            borderStyle = "MODERN_BAR",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 13
        ),
        BiodataTemplate(
            id = "j_mod_purple_14",
            type = BiodataType.JOB,
            name = "Product Leader Violet",
            category = "Modern",
            isPaid = true,
            price = 49,
            layoutType = "TWO_COLUMN",
            primaryColorHex = "#6D28D9",
            secondaryColorHex = "#F5F3FF",
            accentColorHex = "#A78BFA",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 14
        ),
        BiodataTemplate(
            id = "j_mod_amber_15",
            type = BiodataType.JOB,
            name = "Growth Marketer Amber",
            category = "Creative",
            isPaid = false,
            price = 0,
            layoutType = "CREATIVE_ACCENT",
            primaryColorHex = "#B45309",
            secondaryColorHex = "#FFFBEB",
            accentColorHex = "#FBBF24",
            borderStyle = "NONE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 15
        ),
        BiodataTemplate(
            id = "j_mod_split_16",
            type = BiodataType.JOB,
            name = "Split Tone Dual Column",
            category = "Modern",
            isPaid = true,
            price = 29,
            layoutType = "SIDEBAR_RIGHT",
            primaryColorHex = "#1E293B",
            secondaryColorHex = "#F1F5F9",
            accentColorHex = "#0284C7",
            borderStyle = "MODERN_BAR",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 16
        ),
        BiodataTemplate(
            id = "j_mod_cyber_17",
            type = BiodataType.JOB,
            name = "Fintech Cyan Matrix",
            category = "Modern",
            isPaid = true,
            price = 49,
            layoutType = "SIDEBAR_LEFT",
            primaryColorHex = "#0E7490",
            secondaryColorHex = "#ECFEFF",
            accentColorHex = "#06B6D4",
            borderStyle = "MODERN_BAR",
            headerStyle = "CORPORATE",
            fontStyle = "SANS",
            displayOrder = 17
        ),
        BiodataTemplate(
            id = "j_mod_mono_18",
            type = BiodataType.JOB,
            name = "Architect Monochrome",
            category = "Creative",
            isPaid = false,
            price = 0,
            layoutType = "MAGAZINE",
            primaryColorHex = "#18181B",
            secondaryColorHex = "#F4F4F5",
            accentColorHex = "#71717A",
            borderStyle = "NONE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 18
        ),
        BiodataTemplate(
            id = "j_mod_copper_19",
            type = BiodataType.JOB,
            name = "Media Producer Copper",
            category = "Creative",
            isPaid = true,
            price = 39,
            layoutType = "TWO_COLUMN",
            primaryColorHex = "#9A3412",
            secondaryColorHex = "#FFF7ED",
            accentColorHex = "#FB923C",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 19
        ),
        BiodataTemplate(
            id = "j_mod_forest_20",
            type = BiodataType.JOB,
            name = "Biotech Evergreen",
            category = "Modern",
            isPaid = false,
            price = 0,
            layoutType = "CLASSIC_HEADER",
            primaryColorHex = "#166534",
            secondaryColorHex = "#F0FDF4",
            accentColorHex = "#22C55E",
            borderStyle = "HAIRLINE",
            headerStyle = "CORPORATE",
            fontStyle = "SANS",
            displayOrder = 20
        ),

        // 21 - 30: ATS-Inspired & Clean Resume
        BiodataTemplate(
            id = "j_ats_standard_21",
            type = BiodataType.JOB,
            name = "ATS Machine Scannable",
            category = "ATS-Inspired",
            isPaid = false,
            price = 0,
            layoutType = "ATS_CLEAN",
            primaryColorHex = "#111827",
            secondaryColorHex = "#F9FAFB",
            accentColorHex = "#374151",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 21
        ),
        BiodataTemplate(
            id = "j_ats_navy_22",
            type = BiodataType.JOB,
            name = "ATS Top Ranked Blue",
            category = "ATS-Inspired",
            isPaid = false,
            price = 0,
            layoutType = "ATS_CLEAN",
            primaryColorHex = "#1E40AF",
            secondaryColorHex = "#EFF6FF",
            accentColorHex = "#2563EB",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 22
        ),
        BiodataTemplate(
            id = "j_ats_recruiter_23",
            type = BiodataType.JOB,
            name = "6-Second Recruiter Glance",
            category = "ATS-Inspired",
            isPaid = true,
            price = 29,
            layoutType = "ATS_CLEAN",
            primaryColorHex = "#0F766E",
            secondaryColorHex = "#F0FDFA",
            accentColorHex = "#14B8A6",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 23
        ),
        BiodataTemplate(
            id = "j_ats_harvard_24",
            type = BiodataType.JOB,
            name = "Ivy League Standard",
            category = "ATS-Inspired",
            isPaid = true,
            price = 39,
            layoutType = "ATS_CLEAN",
            primaryColorHex = "#000000",
            secondaryColorHex = "#FFFFFF",
            accentColorHex = "#4B5563",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SERIF",
            displayOrder = 24
        ),
        BiodataTemplate(
            id = "j_ats_tech_25",
            type = BiodataType.JOB,
            name = "FAANG Certified Clean",
            category = "ATS-Inspired",
            isPaid = false,
            price = 0,
            layoutType = "ATS_CLEAN",
            primaryColorHex = "#1E293B",
            secondaryColorHex = "#F8FAFC",
            accentColorHex = "#3B82F6",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 25
        ),
        BiodataTemplate(
            id = "j_ats_compact_26",
            type = BiodataType.JOB,
            name = "Single Page ATS Fit",
            category = "ATS-Inspired",
            isPaid = true,
            price = 29,
            layoutType = "COMPACT_GRID",
            primaryColorHex = "#27272A",
            secondaryColorHex = "#FAFAFA",
            accentColorHex = "#71717A",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 26
        ),
        BiodataTemplate(
            id = "j_ats_law_27",
            type = BiodataType.JOB,
            name = "Legal Counsel Format",
            category = "ATS-Inspired",
            isPaid = false,
            price = 0,
            layoutType = "ATS_CLEAN",
            primaryColorHex = "#312E81",
            secondaryColorHex = "#EEF2FF",
            accentColorHex = "#4338CA",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SERIF",
            displayOrder = 27
        ),
        BiodataTemplate(
            id = "j_ats_health_28",
            type = BiodataType.JOB,
            name = "Clinical Medical CV",
            category = "ATS-Inspired",
            isPaid = true,
            price = 39,
            layoutType = "CLASSIC_HEADER",
            primaryColorHex = "#0369A1",
            secondaryColorHex = "#F0F9FF",
            accentColorHex = "#0284C7",
            borderStyle = "HAIRLINE",
            headerStyle = "CORPORATE",
            fontStyle = "SANS",
            displayOrder = 28
        ),
        BiodataTemplate(
            id = "j_ats_finance_29",
            type = BiodataType.JOB,
            name = "Chartered Accountant Form",
            category = "ATS-Inspired",
            isPaid = false,
            price = 0,
            layoutType = "ATS_CLEAN",
            primaryColorHex = "#134E4A",
            secondaryColorHex = "#F0FDFA",
            accentColorHex = "#0D9488",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 29
        ),
        BiodataTemplate(
            id = "j_ats_research_30",
            type = BiodataType.JOB,
            name = "Scientist & Research CV",
            category = "ATS-Inspired",
            isPaid = true,
            price = 49,
            layoutType = "CLASSIC_HEADER",
            primaryColorHex = "#1F2937",
            secondaryColorHex = "#F9FAFB",
            accentColorHex = "#6B7280",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SERIF",
            displayOrder = 30
        ),

        // 31 - 40: Fresh Graduate & Entry Level
        BiodataTemplate(
            id = "j_grad_starter_31",
            type = BiodataType.JOB,
            name = "Campus Placement Ready",
            category = "Fresh Graduate",
            isPaid = false,
            price = 0,
            layoutType = "SIDEBAR_LEFT",
            primaryColorHex = "#2563EB",
            secondaryColorHex = "#EFF6FF",
            accentColorHex = "#3B82F6",
            borderStyle = "MODERN_BAR",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 31
        ),
        BiodataTemplate(
            id = "j_grad_intern_32",
            type = BiodataType.JOB,
            name = "Internship Showcase",
            category = "Fresh Graduate",
            isPaid = false,
            price = 0,
            layoutType = "TWO_COLUMN",
            primaryColorHex = "#059669",
            secondaryColorHex = "#ECFDF5",
            accentColorHex = "#10B981",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 32
        ),
        BiodataTemplate(
            id = "j_grad_btech_33",
            type = BiodataType.JOB,
            name = "Engineering Fresher Hub",
            category = "Fresh Graduate",
            isPaid = true,
            price = 29,
            layoutType = "EXECUTIVE_CORPORATE",
            primaryColorHex = "#1D4ED8",
            secondaryColorHex = "#DBEAFE",
            accentColorHex = "#2563EB",
            borderStyle = "MODERN_BAR",
            headerStyle = "CORPORATE",
            fontStyle = "SANS",
            displayOrder = 33
        ),
        BiodataTemplate(
            id = "j_grad_mba_34",
            type = BiodataType.JOB,
            name = "Management Trainee Pro",
            category = "Fresh Graduate",
            isPaid = true,
            price = 39,
            layoutType = "SIDEBAR_LEFT",
            primaryColorHex = "#7C2D12",
            secondaryColorHex = "#FFEDD5",
            accentColorHex = "#C2410C",
            borderStyle = "MODERN_BAR",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 34
        ),
        BiodataTemplate(
            id = "j_grad_bcom_35",
            type = BiodataType.JOB,
            name = "Commerce & Banking Entry",
            category = "Fresh Graduate",
            isPaid = false,
            price = 0,
            layoutType = "CLASSIC_HEADER",
            primaryColorHex = "#1F2937",
            secondaryColorHex = "#F3F4F6",
            accentColorHex = "#4B5563",
            borderStyle = "HAIRLINE",
            headerStyle = "CORPORATE",
            fontStyle = "SANS",
            displayOrder = 35
        ),
        BiodataTemplate(
            id = "j_grad_arts_36",
            type = BiodataType.JOB,
            name = "Humanities & Writing Folio",
            category = "Fresh Graduate",
            isPaid = false,
            price = 0,
            layoutType = "MINIMAL_PORTRAIT",
            primaryColorHex = "#581C87",
            secondaryColorHex = "#FAF5FF",
            accentColorHex = "#9333EA",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SERIF",
            displayOrder = 36
        ),
        BiodataTemplate(
            id = "j_grad_poly_37",
            type = BiodataType.JOB,
            name = "Diploma & Technical Trades",
            category = "Fresh Graduate",
            isPaid = false,
            price = 0,
            layoutType = "TWO_COLUMN",
            primaryColorHex = "#374151",
            secondaryColorHex = "#F9FAFB",
            accentColorHex = "#0284C7",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 37
        ),
        BiodataTemplate(
            id = "j_grad_sales_38",
            type = BiodataType.JOB,
            name = "Sales Associate Dynamic",
            category = "Fresh Graduate",
            isPaid = true,
            price = 29,
            layoutType = "CREATIVE_ACCENT",
            primaryColorHex = "#DC2626",
            secondaryColorHex = "#FEF2F2",
            accentColorHex = "#EF4444",
            borderStyle = "NONE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 38
        ),
        BiodataTemplate(
            id = "j_grad_bca_39",
            type = BiodataType.JOB,
            name = "Software Developer Junior",
            category = "Fresh Graduate",
            isPaid = true,
            price = 39,
            layoutType = "SIDEBAR_RIGHT",
            primaryColorHex = "#0F766E",
            secondaryColorHex = "#F0FDFA",
            accentColorHex = "#0D9488",
            borderStyle = "MODERN_BAR",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 39
        ),
        BiodataTemplate(
            id = "j_grad_startup_40",
            type = BiodataType.JOB,
            name = "Early Startup Generalist",
            category = "Fresh Graduate",
            isPaid = false,
            price = 0,
            layoutType = "COMPACT_GRID",
            primaryColorHex = "#4338CA",
            secondaryColorHex = "#EEF2FF",
            accentColorHex = "#6366F1",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 40
        ),

        // 41 - 55: Experienced & Dark Theme
        BiodataTemplate(
            id = "j_dark_matrix_41",
            type = BiodataType.JOB,
            name = "Dark Cyber Specialist",
            category = "Dark Luxury",
            isPaid = true,
            price = 69,
            layoutType = "DARK_LUXURY",
            primaryColorHex = "#0B0F19",
            secondaryColorHex = "#111827",
            accentColorHex = "#38BDF8",
            backgroundColorHex = "#0F172A",
            borderStyle = "HAIRLINE",
            headerStyle = "CORPORATE",
            fontStyle = "SANS",
            displayOrder = 41
        ),
        BiodataTemplate(
            id = "j_dark_gold_42",
            type = BiodataType.JOB,
            name = "Midnight Gold Consultant",
            category = "Dark Luxury",
            isPaid = true,
            price = 89,
            layoutType = "DARK_LUXURY",
            primaryColorHex = "#18181B",
            secondaryColorHex = "#27272A",
            accentColorHex = "#FBBF24",
            backgroundColorHex = "#121212",
            borderStyle = "DOUBLE_GOLD",
            headerStyle = "CORPORATE",
            fontStyle = "SERIF",
            displayOrder = 42
        ),
        BiodataTemplate(
            id = "j_dark_emerald_43",
            type = BiodataType.JOB,
            name = "Dark Forest Fintech",
            category = "Dark Luxury",
            isPaid = true,
            price = 59,
            layoutType = "DARK_LUXURY",
            primaryColorHex = "#064E3B",
            secondaryColorHex = "#022C22",
            accentColorHex = "#34D399",
            backgroundColorHex = "#042F24",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 43
        ),
        BiodataTemplate(
            id = "j_exp_lead_44",
            type = BiodataType.JOB,
            name = "Principal Architect Timeline",
            category = "Experienced Professional",
            isPaid = false,
            price = 0,
            layoutType = "SIDEBAR_LEFT",
            primaryColorHex = "#1E3A8A",
            secondaryColorHex = "#F1F5F9",
            accentColorHex = "#2563EB",
            borderStyle = "MODERN_BAR",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 44
        ),
        BiodataTemplate(
            id = "j_exp_vp_45",
            type = BiodataType.JOB,
            name = "VP Operations Milestone",
            category = "Experienced Professional",
            isPaid = true,
            price = 49,
            layoutType = "EXECUTIVE_CORPORATE",
            primaryColorHex = "#0F172A",
            secondaryColorHex = "#F8FAFC",
            accentColorHex = "#3B82F6",
            borderStyle = "MODERN_BAR",
            headerStyle = "CORPORATE",
            fontStyle = "SANS",
            displayOrder = 45
        ),
        BiodataTemplate(
            id = "j_exp_consultant_46",
            type = BiodataType.JOB,
            name = "Senior Advisor Columnar",
            category = "Experienced Professional",
            isPaid = false,
            price = 0,
            layoutType = "TWO_COLUMN",
            primaryColorHex = "#334155",
            secondaryColorHex = "#F8FAFC",
            accentColorHex = "#64748B",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SERIF",
            displayOrder = 46
        ),
        BiodataTemplate(
            id = "j_exp_techlead_47",
            type = BiodataType.JOB,
            name = "Staff Engineer Stack",
            category = "Experienced Professional",
            isPaid = true,
            price = 39,
            layoutType = "SIDEBAR_RIGHT",
            primaryColorHex = "#312E81",
            secondaryColorHex = "#EEF2FF",
            accentColorHex = "#4F46E5",
            borderStyle = "MODERN_BAR",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 47
        ),
        BiodataTemplate(
            id = "j_exp_product_48",
            type = BiodataType.JOB,
            name = "Head of Product Metric",
            category = "Experienced Professional",
            isPaid = false,
            price = 0,
            layoutType = "CREATIVE_ACCENT",
            primaryColorHex = "#4C1D95",
            secondaryColorHex = "#FAF5FF",
            accentColorHex = "#7C3AED",
            borderStyle = "NONE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 48
        ),
        BiodataTemplate(
            id = "j_exp_hr_49",
            type = BiodataType.JOB,
            name = "Chief People Officer",
            category = "Experienced Professional",
            isPaid = true,
            price = 39,
            layoutType = "CLASSIC_HEADER",
            primaryColorHex = "#701A75",
            secondaryColorHex = "#FDF4FF",
            accentColorHex = "#A21CAF",
            borderStyle = "HAIRLINE",
            headerStyle = "CORPORATE",
            fontStyle = "SERIF",
            displayOrder = 49
        ),
        BiodataTemplate(
            id = "j_exp_legal_50",
            type = BiodataType.JOB,
            name = "General Counsel Senior",
            category = "Experienced Professional",
            isPaid = false,
            price = 0,
            layoutType = "CLASSIC_HEADER",
            primaryColorHex = "#1C1917",
            secondaryColorHex = "#FAFAF9",
            accentColorHex = "#57534E",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SERIF",
            displayOrder = 50
        ),
        BiodataTemplate(
            id = "j_exp_creative_51",
            type = BiodataType.JOB,
            name = "Creative Director Folio",
            category = "Creative",
            isPaid = true,
            price = 49,
            layoutType = "MAGAZINE",
            primaryColorHex = "#09090B",
            secondaryColorHex = "#F4F4F5",
            accentColorHex = "#E11D48",
            borderStyle = "NONE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 51
        ),
        BiodataTemplate(
            id = "j_exp_supply_52",
            type = BiodataType.JOB,
            name = "Supply Chain Maestro",
            category = "Experienced Professional",
            isPaid = false,
            price = 0,
            layoutType = "TWO_COLUMN",
            primaryColorHex = "#0C4A6E",
            secondaryColorHex = "#F0F9FF",
            accentColorHex = "#0284C7",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 52
        ),
        BiodataTemplate(
            id = "j_exp_marketing_53",
            type = BiodataType.JOB,
            name = "Chief Marketing Officer",
            category = "Experienced Professional",
            isPaid = true,
            price = 59,
            layoutType = "EXECUTIVE_CORPORATE",
            primaryColorHex = "#831843",
            secondaryColorHex = "#FDF2F8",
            accentColorHex = "#DB2777",
            borderStyle = "MODERN_BAR",
            headerStyle = "CORPORATE",
            fontStyle = "SANS",
            displayOrder = 53
        ),
        BiodataTemplate(
            id = "j_exp_compact_54",
            type = BiodataType.JOB,
            name = "Dense Dual Column Master",
            category = "Experienced Professional",
            isPaid = false,
            price = 0,
            layoutType = "COMPACT_GRID",
            primaryColorHex = "#262626",
            secondaryColorHex = "#FAFAFA",
            accentColorHex = "#525252",
            borderStyle = "HAIRLINE",
            headerStyle = "SIMPLE",
            fontStyle = "SANS",
            displayOrder = 54
        ),
        BiodataTemplate(
            id = "j_exp_gold_55",
            type = BiodataType.JOB,
            name = "Summit President Signature",
            category = "Executive",
            isPaid = true,
            price = 79,
            layoutType = "EXECUTIVE_CORPORATE",
            primaryColorHex = "#18181B",
            secondaryColorHex = "#FDFBF7",
            accentColorHex = "#D97706",
            borderStyle = "DOUBLE_GOLD",
            headerStyle = "CORPORATE",
            fontStyle = "SERIF",
            displayOrder = 55
        )
    )

    // In-memory or dynamic override state for Admin changes
    private val templateOverrides = mutableMapOf<String, BiodataTemplate>()

    fun getAllTemplates(): List<BiodataTemplate> {
        val baseList = marriageTemplates + jobTemplates
        return baseList.map { templateOverrides[it.id] ?: it }
    }

    fun getTemplatesByType(type: BiodataType): List<BiodataTemplate> {
        val baseList = if (type == BiodataType.MARRIAGE) marriageTemplates else jobTemplates
        return baseList.map { templateOverrides[it.id] ?: it }
    }

    fun getTemplateById(id: String): BiodataTemplate {
        templateOverrides[id]?.let { return it }
        return (marriageTemplates + jobTemplates).firstOrNull { it.id == id }
            ?: marriageTemplates.first()
    }

    fun updateTemplate(template: BiodataTemplate) {
        templateOverrides[template.id] = template
    }

    fun resetToDefaults() {
        templateOverrides.clear()
    }

    fun getCategories(type: BiodataType): List<String> {
        return getTemplatesByType(type)
            .map { it.category }
            .distinct()
    }
}
